<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\ProjectApp.Domain\ProjectApp.Domain.csproj" />
  </ItemGroup>
	
	<ItemGroup>
		<FrameworkReference Include="Microsoft.AspNetCore.App" />
	</ItemGroup>
	
  <ItemGroup>
    <PackageReference Include="FluentValidation" Version="9.5.4" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="9.5.4" />
    <PackageReference Include="Mapster" Version="10.0.9" />
    <PackageReference Include="MediatR" Version="12.5.0" />
    <PackageReference Include="Microsoft.AspNetCore.Hosting.Abstractions" Version="2.3.13" />
    <PackageReference Include="Microsoft.Extensions.Identity.Core" Version="9.0.20" />
  </ItemGroup>

</Project>
