<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>e9d5773e-8361-45a9-b8e3-c2a86d5c51a9</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Services\ProductServices\" />
  </ItemGroup>

</Project>
